### ISSUE TITLE
plugin should report metrics continuously

### ISSUE THREAD

**Issue by alespour** [bonitoo-io/telegraf-input-db2#1]
This plugin has the same "issue" as [telegraf-input-oracle #1](https://github.com/bonitoo-io/telegraf-input-oracle/issues/1) - it should report metrics continuously but it's one-shot. Therefore, error that process exited is logged every `restart_delay` interval and started again.

**Comment by alespour** [comment]
[dtto](https://github.com/bonitoo-io/telegraf-input-oracle/issues/1#issuecomment-959504083) here

**Comment by sranka** [comment]
Thank you for the investigation, I'd be glad to review a PR and approve your changes.
